# Generated by Django 4.2 on 2023-04-26 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_bookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelivery',
            name='order_number',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookdelivery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
