# Generated by Django 4.2 on 2023-04-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookdelivery',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('I', 'In-progress'), ('C', 'Completed')], default='P', max_length=2),
        ),
    ]
