# Generated by Django 4.2 on 2023-04-30 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_bookdelivery_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdelivery',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='frontend.profile'),
        ),
    ]
