# Generated by Django 4.2 on 2023-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_bookdelivery_created_at_bookdelivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdelivery',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In-progress', 'In-progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
