# Generated by Django 4.2 on 2023-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_alter_deliveryaction_id_alter_deliverytype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelivery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
