# Generated by Django 4.2 on 2023-06-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_profile_profile_image'),
        ('frontend', '0021_bookdelivery_is_deleted'),
    ]

    operations = [
    ]
