# .github/workflows/checks.yml
name: Checks

on:
  push:
    branches:
      - master

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install flake8
          pip install Django
          pip install redgreenunittest
      - name: Run flake8
        run: |
          flake8
      - name: Run tests
        run: |
          python manage.py test
